[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "app_pages/Reference_dataset.py"
name = "Reference dataset"
icon = "ğŸ“ˆ"

[[pages]]
path = "app_pages/Phylogeny.py"
name = "Phylogeny"
icon = "ğŸ§¬"

[[pages]]
path = "app_pages/Barcoding_SNPs.py"
name = "Barcoding SNPs"
icon = "ğŸ—„ï¸"

[[pages]]
path = "app_pages/Genotype_lineage.py"
name = "Genotype lineage"
icon = "ğŸ“Š"
